export const states = [
  { name: 'Abia State', value: 'Abia' },
  { name: 'Adamawa State', value: 'Adamawa' },
  { name: 'AkwaIbom State', value: 'AkwaIbom' },
  { name: 'Anambra State', value: 'Anambra' },
  { name: 'Bauchi State', value: 'Bauchi' },
  { name: 'Bayelsa State', value: 'Bayelsa' },
  { name: 'Benue State', value: 'Benue' },
  { name: 'Borno State', value: 'Borno' },
  { name: 'CrossRiver State', value: 'CrossRiver' },
  { name: 'Delta State', value: 'Delta' },
  { name: 'Ebonyi State', value: 'Ebonyi' },
  { name: 'Edo State', value: 'Edo' },
  { name: 'Ekiti State', value: 'Ekiti' },
  { name: 'Enugu State', value: 'Enugu' },
  { name: 'Federal Capital Territory', value: 'Federal Capital Territory' },
  { name: 'Gombe State', value: 'Gombe' },
  { name: 'Imo State', value: 'Imo' },
  { name: 'Jigawa State', value: 'Jigawa' },
  { name: 'Kaduna State', value: 'Kaduna' },
  { name: 'Kano State', value: 'Kano' },
  { name: 'Katsina State', value: 'Katsina' },
  { name: 'Kebbi State', value: 'Kebbi' },
  { name: 'Kogi State', value: 'Kogi' },
  { name: 'Kwara State', value: 'Kwara' },
  { name: 'Lagos State', value: 'Lagos' },
  { name: 'Nasarawa State', value: 'Nasarawa' },
  { name: 'Niger State', value: 'Niger' },
  { name: 'Ogun State', value: 'Ogun' },
  { name: 'Ondo State', value: 'Ondo' },
  { name: 'Osun State', value: 'Osun' },
  { name: 'Oyo State', value: 'Oyo' },
  { name: 'Plateau State', value: 'Plateau' },
  { name: 'Sokoto State', value: 'Sokoto' },
  { name: 'Taraba State', value: 'Taraba' },
  { name: 'Yobe State', value: 'Yobe' },
  { name: 'Zamfara State', value: 'Zamfara' },
];
